-- 0008_share_slug.sql — public/unlisted shareable slug for КСП.
--
-- Adds a stable, unguessable short slug to every lesson plan so it can be
-- linked from outside the editor (`/p/<slug>`). The slug:
--   * is generated by the application (12 chars of url-safe base64);
--   * is null until the user explicitly hits "Поделиться" — keeps the
--     URL surface small for plans that have never been shared;
--   * unique across all plans.
--
-- RLS: in addition to the existing "public" select policy we add an
-- "unlisted" select policy. Unlisted plans are readable by anyone (including
-- anonymous users) — but the slug acts as the secret because it's not
-- enumerable from the UI and URLs are only handed out by the owner.

alter table public.lesson_plans
  add column if not exists slug text;

create unique index if not exists lesson_plans_slug_uniq
  on public.lesson_plans (slug)
  where slug is not null;

-- Drop and recreate to be idempotent if this migration is replayed.
drop policy if exists "lesson_plans: unlisted readable with slug"
  on public.lesson_plans;

create policy "lesson_plans: unlisted readable with slug"
  on public.lesson_plans for select
  using (
    visibility = 'unlisted'
    and slug is not null
  );
